@echo off
echo Adding remote origin...
git remote add origin https://github.com/Abumuktar/Retayn.git
echo Setting branch to main...
git branch -M main
echo Pushing to GitHub...
git push -u origin main
echo Done.
